### ISSUE TITLE
Error building or serving

### ISSUE THREAD

**Issue by mikeerickson** [DHTMLX/vue-scheduler-demo#8]
When running `npm run serve` the following errors are thrown.  Not sure if you all have tested this will current version of vue, etc. 

```bash

  Building for production...

 ERROR  Failed to compile with 1 errors                                                                                 8:18:23 PM

 error  in ./src/main.js

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
[BABEL] /Users/mikee/Documents/code/js/vue/vue-scheduler-demo/src/main.js: No "exports" main resolved in /Users/mikee/Documents/code/js/vue/vue-scheduler-demo/node_modules/@babel/helper-compilation-targets/package.json (While processing: "/Users/mikee/Documents/code/js/vue/vue-scheduler-demo/node_modules/@vue/cli-plugin-babel/preset.js")
    at PoolWorker.fromErrorObj (/Users/mikee/Documents/code/js/vue/vue-scheduler-demo/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /Users/mikee/Documents/code/js/vue/vue-scheduler-demo/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at applyExports (internal/modules/cjs/loader.js:498:9)
    at resolveExports (internal/modules/cjs/loader.js:514:23)
    at Function.Module._findPath (internal/modules/cjs/loader.js:642:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1017:27)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/mikee/Documents/code/js/vue/vue-scheduler-demo/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)

 @ multi ./src/main.js

 ERROR  Build failed with errors.

```

**Comment by ArtiBorisevich** [comment]
Hello,
This error can occur if dependency versions conflict with the Node.JS. The issue is usually solved by removing the `yarn.lock` file and reinstalling node modules.
